name: Sample actions

on:
  push:
    branches: master # mainの場合はmainブランチ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

